Updated 400 error message content and handling
retaildevcrews/helium-typescript pull request #215
Opened 2020-10-01 17:50 UTC by PurpleBriar

## Type of PR

- [ ] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

### Purpose of PR
Updated 400 error messages to be conform to standardized JSON format.

### Validation
- [ ] Unit tests updated and ran successfully
- [x] Update documentation or issue referenced above

### Issues Closed or Referenced

- References #helium/issues/514

2020-10-01 17:58 UTC, aflinchb commented on src/utilities/parameterValidationUtilities.ts
> +export class ParameterValidationUtilities {
Is there a reason a new validation utility was created? There is the existing validationUtilities.ts

2020-10-01 18:03 UTC, jasonshave commented on src/utilities/apiValidationUtilities.ts
> +            "status": 400,
is it possible to use something like `(int)HttpStatusCode.BadRequest` instead of the int?

2020-10-01 18:07 UTC, jasonshave commented on src/utilities/apiValidationUtilities.ts
> +            "instance": actorId,
does this `instance` produce the route path for the direct read to actors and does it pass the web validate bad.json tests?

2020-10-01 18:10 UTC, jasonshave reviewed
I don't have the TypeScript background to understand if the solution provided can be refactored or not. I have reviewed the essence of the code and it appears to align with the task's objectives.

2020-10-01 18:33 UTC, alfredoihernandez commented on src/config/constants.ts
> +    invalidMovieIDMessage: "The parameter 'movieId' should start with 'tt' and be between 7 and 11 characters in total.",
might be worth moving to one of the new classes

2020-10-01 18:35 UTC, alfredoihernandez commented on src/utilities/apiValidationUtilities.ts
> +        const queryString = APIValidationUtilities.buildQueryString("/api/actors?", query);
would be nice to see path come in like query from controller

2020-10-01 18:36 UTC, alfredoihernandez commented on src/utilities/apiValidationUtilities.ts
> +            "instance": queryString, //"/api/actors?q=a&pageSize=99999",
remove comment?

2020-10-01 18:38 UTC, alfredoihernandez commented on src/utilities/parameterValidationUtilities.ts
> +    public static validateQ(query: any) {
any ways to shorten these functions as lots of code is duplicated?

2020-10-01 18:52 UTC, PurpleBriar commented on src/utilities/parameterValidationUtilities.ts
> +export class ParameterValidationUtilities {
I split validationUtilities into two files, so I could reuse the parameter validation functions, since we are now reporting all of the errors found by a query, instead of the first error. The first file (parameterValidationUtilities) just has functions that run the individual parameter validation checks and return the error messages for those checks, while the second one (apiValidationUtilities) runs the combinations of checks relevant to the query and compiles the errors (if any) into a single message. I used this approach because the JSON form changed a lot, and I had to find a flexible way of compiling the error messages.

2020-10-01 18:56 UTC, PurpleBriar commented on src/utilities/apiValidationUtilities.ts
> +            "status": 400,
Thanks for catching that. I've updated it.

2020-10-01 19:06 UTC, aflinchb commented on src/utilities/apiValidationUtilities.ts
> +        return output.substring(0, output.length-1);
remove "//console.log(query);" comment

2020-10-01 19:07 UTC, aflinchb commented on src/controllers/MovieController.ts
You can remove line 8 and add to line 7, so would be:  "import { getHttpStatusCode, APIValidationUtilities } from "../utilities";" (same with ActorController.ts)

2020-10-01 19:12 UTC, aflinchb commented on src/utilities/parameterValidationUtilities.ts
> +export class ParameterValidationUtilities {
That seems fine, but we should remove the original validiationUtilities.ts file as it doesn't appear to be used anymore.

2020-10-01 19:29 UTC, PurpleBriar commented on src/controllers/MovieController.ts
I tried that initially, but I got the error:

_**Module '"../utilities"' has no exported member 'APIValidationUtilities'**_

Is there anything else I need to add in the class definition?

2020-10-01 20:43 UTC, PurpleBriar commented on src/utilities/apiValidationUtilities.ts
> +            "instance": actorId,
I update this to read the route path from the Request object.

2020-10-01 20:44 UTC, PurpleBriar commented on src/utilities/apiValidationUtilities.ts
> +            "instance": actorId,
Passes webv, but I found an issue with webv testing that needs to be debugged.

2020-10-01 20:45 UTC, PurpleBriar commented on src/utilities/parameterValidationUtilities.ts
> +export class ParameterValidationUtilities {
Removed validationUtilities

2020-10-01 20:45 UTC, PurpleBriar commented on src/utilities/apiValidationUtilities.ts
> +        const queryString = APIValidationUtilities.buildQueryString("/api/actors?", query);
Updated to retrieve path from controller.

2020-10-01 20:46 UTC, PurpleBriar commented on src/controllers/MovieController.ts
Thanks, I've updated this.

2020-10-01 21:26 UTC, PurpleBriar commented on src/config/constants.ts
> +    invalidMovieIDMessage: "The parameter 'movieId' should start with 'tt' and be between 7 and 11 characters in total.",
Moved them to parameterValidationUtilities.

2020-10-02 15:07 UTC, aflinchb commented on src/utilities/apiValidationUtilities.ts
> +    public static validateActors(query: any, path: string, querySuffix: string) {
Update comment to match function.  Although it is validating common parameters, the function is defined as specific to actors

2020-10-02 15:10 UTC, aflinchb commented on test/unit/utilities.tests.ts
>        it("should validate with no parameters", () => {
update describe to "validateActors"

2020-10-02 17:55 UTC, alfredoihernandez approved these changes

2020-10-02 18:25 UTC, aflinchb requested changes
Movie and Actor queries with valid parameters are returning 500 for me (i.e. /api/actors , /api/movies)

2020-10-02 20:02 UTC, aflinchb approved these changes
Approved - pending WebV validation.  

We can follow up at stand up to discuss the best design moving forward (i.e. adding the custom formatter vs. using the res.write like with healthz).

2020-10-05 14:11 UTC, merged